source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MKLabel_Example', :exclusive => true do
  pod 'MKLabel', :path => '../'
end

target 'MKLabel_Tests', :exclusive => true do
  pod 'MKLabel', :path => '../'

  
end
